export GUID=...
export CLIENT_ID=...
export PASSWORD=...
export TENANT=...
export SUBSCRIPTION=...
export RESOURCEGROUP=...

# Optionally install Azure CLI if not present already
# curl -L https://aka.ms/InstallAzureCli | bash

